version: "3"

services:
  ssh-server:
    image: ghcr.io/mazrean/ssh-separator:latest
    environment:
      API_KEY: api_key # key for the REST API. you need to rewrite this in production.
    ports:
      - 2222:2222
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # docker outside of docker
